# Generated by Django 5.2.4 on 2025-07-08 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_versao', models.CharField(max_length=100, unique=True)),
                ('arquivo_modelo', models.FileField(upload_to='ml_models/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, help_text='Define se este é o modelo em produção.')),
                ('acuracia_validacao', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_lesao', models.ImageField(upload_to='lesoes/%Y/%m/%d/')),
                ('resultado_classificacao', models.CharField(blank=True, choices=[('HANSENIASE', 'Hanseníase'), ('MELANOMA', 'Melanoma'), ('NEVO', 'Nevo (Benigno)')], max_length=15, null=True)),
                ('confianca', models.FloatField(blank=True, null=True)),
                ('data_laudo', models.DateTimeField(auto_now_add=True)),
                ('perda_sensibilidade_termica', models.BooleanField(default=False)),
                ('apresenta_nodulos', models.BooleanField(default=False)),
                ('observacoes_clinicas', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paciente')),
                ('modelo_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laudos.modeloml')),
            ],
        ),
    ]
