# Generated by Django 5.2.4 on 2025-07-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='resultado_classificacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
