# Generated by Django 5.2.4 on 2025-07-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0002_alter_laudo_resultado_classificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloml',
            name='acuracia_validacao',
        ),
        migrations.AddField(
            model_name='modeloml',
            name='acuracia',
            field=models.FloatField(blank=True, help_text='Acurácia geral do modelo', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='auc_roc',
            field=models.FloatField(blank=True, help_text='Área sob a curva ROC', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='cenario_clinico',
            field=models.CharField(blank=True, help_text='Descrição do cenário de diagnóstico para o qual este modelo foi treinado.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='especificidade',
            field=models.FloatField(blank=True, help_text='Especificidade média (TNR)', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='kappa',
            field=models.FloatField(blank=True, help_text='Índice Kappa de Cohen', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='matriz_confusao_img',
            field=models.ImageField(blank=True, null=True, upload_to='reports/confusion_matrix/'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='parametros_treinamento',
            field=models.JSONField(blank=True, help_text='Parâmetros do formulário usados neste treinamento', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='sensibilidade',
            field=models.FloatField(blank=True, help_text='Sensibilidade média (Recall/TPR)', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='tempo_teste_seg',
            field=models.FloatField(blank=True, help_text='Tempo total para avaliar o conjunto de teste em segundos', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='tempo_treinamento_seg',
            field=models.FloatField(blank=True, help_text='Tempo total de treinamento em segundos', null=True),
        ),
    ]
