# Generated by Django 5.2.4 on 2025-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0003_remove_modeloml_acuracia_validacao_modeloml_acuracia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloml',
            name='acuracia',
        ),
        migrations.RemoveField(
            model_name='modeloml',
            name='auc_roc',
        ),
        migrations.RemoveField(
            model_name='modeloml',
            name='especificidade',
        ),
        migrations.RemoveField(
            model_name='modeloml',
            name='kappa',
        ),
        migrations.RemoveField(
            model_name='modeloml',
            name='sensibilidade',
        ),
        migrations.RemoveField(
            model_name='modeloml',
            name='tempo_teste_seg',
        ),
        migrations.AddField(
            model_name='modeloml',
            name='acuracia_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='acuracia_std',
            field=models.FloatField(blank=True, help_text='Desvio padrão da acurácia', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='auc_roc_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='auc_roc_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='boxplot_acuracia_img',
            field=models.ImageField(blank=True, null=True, upload_to='reports/boxplots/'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='especificidade_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='especificidade_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='kappa_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='kappa_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='metricas_raw',
            field=models.JSONField(blank=True, help_text='Resultados brutos de cada fold para gerar os box plots', null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='sensibilidade_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='sensibilidade_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeloml',
            name='cenario_clinico',
            field=models.CharField(blank=True, help_text='Descrição do cenário de diagnóstico.', max_length=255, null=True),
        ),
    ]
