# Generated by Django 5.2.4 on 2025-07-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0004_remove_modeloml_acuracia_remove_modeloml_auc_roc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='grad_cam_img',
            field=models.ImageField(blank=True, null=True, upload_to='reports/grad_cam/'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='importancia_features_img',
            field=models.ImageField(blank=True, null=True, upload_to='reports/feature_importance/'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='top_features_json',
            field=models.JSONField(blank=True, help_text='Top 20 features mais importantes e seus scores', null=True),
        ),
    ]
