# Generated by Django 5.2.4 on 2025-07-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0005_laudo_grad_cam_img_modeloml_importancia_features_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloml',
            name='boxplot_auc_roc_img',
            field=models.ImageField(blank=True, null=True, upload_to='reports/boxplots/'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='boxplot_especificidade_img',
            field=models.ImageField(blank=True, null=True, upload_to='reports/boxplots/'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='boxplot_kappa_img',
            field=models.ImageField(blank=True, null=True, upload_to='reports/boxplots/'),
        ),
        migrations.AddField(
            model_name='modeloml',
            name='boxplot_sensibilidade_img',
            field=models.ImageField(blank=True, null=True, upload_to='reports/boxplots/'),
        ),
    ]
