# Generated by Django 5.2.4 on 2025-07-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0006_modeloml_boxplot_auc_roc_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloml',
            name='class_map_json',
            field=models.JSONField(blank=True, help_text="Mapeamento de índice para nome de classe. Ex: {'0': 'caes', '1': 'gatos'}", null=True),
        ),
        migrations.AlterField(
            model_name='modeloml',
            name='acuracia_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeloml',
            name='metricas_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeloml',
            name='tempo_treinamento_seg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeloml',
            name='top_features_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
